---
title: "Quão bom em R preciso SER?"
author: 
- Jonatha Azevedo
- Leonardo Filgueira
output:
  revealjs::revealjs_presentation:
    template: default_mod.html
    self_contained: false
    center: true
    theme: serif
    highlight: pygments
    background_transition: none
    transition: default
    reveal_plugins: ["chalkboard"]
    reveal_options:
      chalkboard:
        theme: whiteboard
        toggleNotesButton: false
---

## Desafios {data-background-image="ser3.png" data-background-size="150px" data-background-position=bottom}

>- Exigência do mercado de trabalho.
>- Abrangência de conteúdos aprendidos na Universidade.
>- Tempo de prática.

## Atitudes {data-background-image="ser3.png" data-background-size="150px" data-background-position=bottom}

>- Organizar tempo de estudo para o R.
>- Ir além do ensinado em aula.
>- Utilizar o *help*.
>- Buscar pacotes.
>- Pesquisar materiais.
>- Participar de projetos.
>- Inglês.

## Busca de pacotes {data-background-image="ser3.png" data-background-size="150px" data-background-position=bottom}

>- Com professores, estagiários e colegas no mercado de trabalho.
>- [Lista de pacotes úteis](https://support.rstudio.com/hc/en-us/articles/201057987-Quick-list-of-useful-R-packages) no site do RStudio.
>- [R bloggers](https://www.r-bloggers.com/).
>- [Blog do RStudio](https://blog.rstudio.com/)

## Materiais {data-background-image="ser3.png" data-background-size="150px" data-background-position=bottom}

>- Vignettes de pacotes.
>- Livro [R for Data science](http://r4ds.had.co.nz/).
>- Cursos do [DataCamp](https://www.datacamp.com).
>- [tryR](http://tryr.codeschool.com), do Code School.
>- [R beginners guide](https://www.computerworld.com/article/2497143/business-intelligence/business-intelligence-beginner-s-guide-to-r-introduction.html).
>- [Webnars](https://www.rstudio.com/resources/webinars/) do RStudio.
>- [Portal](http://www.estatisticacomr.uff.br/) do projeto Estatística é com R!

## Pacotes importantes {data-background-image="ser3.png" data-background-size="150px" data-background-position=bottom}

### Pacotes do [Tidyverse](https://www.tidyverse.org/)

>- [dplyr](http://dplyr.tidyverse.org/)
>- [tidyr](http://tidyr.tidyverse.org/)
>- [ggplot2](http://ggplot2.tidyverse.org/)
>- [stringr](http://stringr.tidyverse.org/)
>- [purrr](http://purrr.tidyverse.org/)

## Pacotes importantes {data-background-image="ser3.png" data-background-size="150px" data-background-position=bottom}

### Outros pacotes

>- [rmarkdown](https://rmarkdown.rstudio.com/)
>- [shiny](https://shiny.rstudio.com/)
>- [dygraphs](https://rstudio.github.io/dygraphs/)
>- [leaflet](https://rstudio.github.io/leaflet/)
>- [ggmap](https://cran.r-project.org/web/packages/ggmap/index.html)
>- [data.table](https://cran.r-project.org/web/packages/data.table/vignettes/datatable-intro.html)

## Busca {data-background-image="ser3.png" data-background-size="150px" data-background-position=bottom}

>- Sempre buscar novas funções e pacotes.
>- Buscar dúvidas no [Stack Overflow](https://stackoverflow.com/).
>- Conhecer o repositório dos pacotes no GitHub.
>- Issues e novas features no github.
>- Participar de eventos.

## Outras ferramentas {data-background-image="ser3.png" data-background-size="150px" data-background-position=bottom}

>- SQL.
>- Git.
>- Phyton.

## Fontes {data-background-image="ser3.png" data-background-size="150px" data-background-position=bottom}

- https://www.rstudio.com/online-learning/#r
- https://support.rstudio.com/hc/en-us/articles/201057987-Quick-list-of-useful-R-packages